[".local/etc/nvim"]
    type = "git-repo"
    url = "https://github.com/erayaydin/NVimArtisan.git"
    refreshPeriod = "168h"
[".local/etc/ranger/plugins/ranger_devicons"]
    type = "git-repo"
    url = "https://github.com/alexanderjeurissen/ranger_devicons.git"
    refreshPeriod = "48h"
